clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules   .\Source\Engine\Module\Reflector.cppm --precompile -o .\Intermediate\Modules\Module_temp\Reflector.pcm
clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules    .\Intermediate\Modules\Module_temp\Reflector.pcm -c -o .\Intermediate\Modules\Module_temp\Reflector_interface.obj
clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules   -fmodule-file=.\Intermediate\Modules\Module_temp\Reflector.pcm .\Intermediate\Modules\Module_temp\Reflector_interface.obj  .\Source\Engine\Module\ModuleEntry.cppm --precompile -o .\Intermediate\Modules\Module_temp\ModuleEntry.pcm
clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules   -fmodule-file=.\Intermediate\Modules\Module_temp\Reflector.pcm .\Intermediate\Modules\Module_temp\Reflector_interface.obj   .\Intermediate\Modules\Module_temp\ModuleEntry.pcm -c -o .\Intermediate\Modules\Module_temp\ModuleEntry_interface.obj
clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules   -fmodule-file=.\Intermediate\Modules\Module_temp\Reflector.pcm  -fmodule-file=.\Intermediate\Modules\Module_temp\ModuleEntry.pcm --precompile -o .\Intermediate\Modules\Module.pcm .\Source\Engine\Module\Module.cppm
clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules   -fmodule-file=.\Intermediate\Modules\Module_temp\Reflector.pcm  -fmodule-file=.\Intermediate\Modules\Module_temp\ModuleEntry.pcm .\Intermediate\Modules\Module_temp\Reflector_interface.obj .\Intermediate\Modules\Module_temp\ModuleEntry_interface.obj -c  .\Source\Engine\Module\Module.cppm -o .\Intermediate\Modules\Module_temp\Module_interface.obj
lld-link  /lib   .\Intermediate\Modules\Module_temp\Reflector_interface.obj .\Intermediate\Modules\Module_temp\ModuleEntry_interface.obj  .\Intermediate\Modules\Module_temp\Module_interface.obj  /out:Intermediate\Modules\Module.lib

clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules  .\Intermediate\Modules\Module.lib .\Intermediate\Modules\Module.lib  .\Source\Engine\Object\Reflector.cppm --precompile -o .\Intermediate\Modules\Object_temp\Reflector.pcm
clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules  .\Intermediate\Modules\Module.lib .\Intermediate\Modules\Module.lib   .\Intermediate\Modules\Object_temp\Reflector.pcm -c -o .\Intermediate\Modules\Object_temp\Reflector_interface.obj
clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules  .\Intermediate\Modules\Module.lib .\Intermediate\Modules\Module.lib  -fmodule-file=.\Intermediate\Modules\Object_temp\Reflector.pcm .\Intermediate\Modules\Object_temp\Reflector_interface.obj  .\Source\Engine\Object\NObject.cppm --precompile -o .\Intermediate\Modules\Object_temp\NObject.pcm
clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules  .\Intermediate\Modules\Module.lib .\Intermediate\Modules\Module.lib  -fmodule-file=.\Intermediate\Modules\Object_temp\Reflector.pcm .\Intermediate\Modules\Object_temp\Reflector_interface.obj   .\Intermediate\Modules\Object_temp\NObject.pcm -c -o .\Intermediate\Modules\Object_temp\NObject_interface.obj
clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules  .\Intermediate\Modules\Module.lib .\Intermediate\Modules\Module.lib  -fmodule-file=.\Intermediate\Modules\Object_temp\Reflector.pcm  -fmodule-file=.\Intermediate\Modules\Object_temp\NObject.pcm --precompile -o .\Intermediate\Modules\Object.pcm .\Source\Engine\Object\Object.cppm
clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules  .\Intermediate\Modules\Module.lib .\Intermediate\Modules\Module.lib  -fmodule-file=.\Intermediate\Modules\Object_temp\Reflector.pcm  -fmodule-file=.\Intermediate\Modules\Object_temp\NObject.pcm .\Intermediate\Modules\Object_temp\Reflector_interface.obj .\Intermediate\Modules\Object_temp\NObject_interface.obj -c  .\Source\Engine\Object\Object.cppm -o .\Intermediate\Modules\Object_temp\Object_interface.obj
lld-link  /lib .\Intermediate\Modules\Module.lib   .\Intermediate\Modules\Object_temp\Reflector_interface.obj .\Intermediate\Modules\Object_temp\NObject_interface.obj  .\Intermediate\Modules\Object_temp\Object_interface.obj  /out:Intermediate\Modules\Object.lib

clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules  .\Intermediate\Modules\Object.lib .\Intermediate\Modules\Object.lib --precompile -o .\Intermediate\Modules\World.pcm .\Source\Engine\World\World.cppm
clang++ -std=c++20 -fmodules  -O3  -Wall   -fprebuilt-module-path=.\Intermediate\Modules  .\Intermediate\Modules\Object.lib .\Intermediate\Modules\Object.lib -c  .\Source\Engine\World\World.cppm -o .\Intermediate\Modules\World_temp\World_interface.obj
lld-link  /lib .\Intermediate\Modules\Object.lib    .\Intermediate\Modules\World_temp\World_interface.obj  /out:Intermediate\Modules\World.lib
